FROM ubuntu:16.04
LABEL maintainer ="a.guillermo.guzman@gmail.com"


RUN apt-get update -y && \
    apt-get upgrade -y && \
    # curl
    apt-get install -y sudo curl && \
    # C
    apt-get install -y build-essential && \
    # These may be unnecessary for the production machine...
    apt-get install -y libkrb5-dev libldap2-dev libsasl2-dev libssl-dev libffi-dev

# Download and build latest version of Python
RUN set -ex && \
    cd /usr/src && \
    curl -O https://www.python.org/ftp/python/2.7.14/Python-2.7.14.tgz && \
    tar xvzf Python-2.7.14.tgz && \
    cd Python-2.7.14 && \
    ./configure && \
    make install

WORKDIR /tmp

ARG CONTINUUM_INSTALLER_LINK

RUN set -xe && \
    cd /tmp && \
    # Download installer
    curl -o install.sh $CONTINUUM_INSTALLER_LINK && \
    chmod +x install.sh && \
    ./install.sh -m -p -s

ENV CONTINUUM_HOME=/opt/continuum/current

EXPOSE 9090:8080
CMD /opt/continuum/current/common/install/init_mongodb.py -p n813KLVh7sLowt08A66tEQ==
