FROM centos:6.9
LABEL maintainer ="a.guillermo.guzman@gmail.com"


RUN yum -y update && \
    yum -y install epel-release && \
    yum -y install make gcc curl && \
    # C libs supporting thirdparty python deps
    yum -y install libffi-devel krb5-devel openldap-devel openssl-devel


# Download and build latest version of Python
RUN set -ex && \
    cd /usr/src && \
    curl -O https://www.python.org/ftp/python/2.7.14/Python-2.7.14.tgz && \
    tar xvzf Python-2.7.14.tgz && \
    cd Python-2.7.14 && \
    ./configure && \
    make install

WORKDIR /tmp

ARG CONTINUUM_INSTALLER_LINK=""

RUN echo $CONTINUUM_INSTALLER_LINK

RUN yum -y install sudo libc6-dev

RUN set -xe && \
    cd /tmp && \
    curl -o install.sh $CONTINUUM_INSTALLER_LINK && \
    head -n 100 install.sh && \
    chmod +x install.sh && \
    sed -i 's/source ${WHICHPROFILE}//g' install.sh && \
    ./install.sh -m -p -s && \
    echo '  mongodb_server: mongodb' >> /etc/continuum/continuum.yaml

ENV CONTINUUM_HOME=/opt/continuum/current

EXPOSE 9090:8080

CMD ["/opt/continuum/current/common/install/init_mongodb.py", "-p", "n813KLVh7sLowt08A66tEQ=="]