FROM ubuntu:16.04
LABEL maintainer ="a.guillermo.guzman@gmail.com"


RUN apt-get update -y && \
    apt-get upgrade -y && \
    # curl
    apt-get install -y curl && \
    # C
    apt-get install -y build-essential sudo && \
    # These may be unnecessary for the production machine...
    apt-get install -y libkrb5-dev libldap2-dev libsasl2-dev libssl-dev libffi-dev

# Download and build latest version of Python
RUN set -ex && \
    cd /usr/src && \
    curl -O https://www.python.org/ftp/python/2.7.14/Python-2.7.14.tgz && \
    tar xvzf Python-2.7.14.tgz && \
    cd Python-2.7.14 && \
    ./configure && \
    make install

WORKDIR /tmp

ENV INSTALLER=""
ARG CONTINUUM_INSTALLER_LINK=$INSTALLER

RUN set -xe && \
    cd /tmp && \
    # Download installer
    curl -o install.sh $INSTALLER && \
    chmod +x install.sh && \
    # Installation wasn't successful until source line was removed
    sed -i 's/source ${WHICHPROFILE}//g' install.sh && \
    # Silent, skip data initialization, skip starting services
    ./install.sh -m -p -s && \
    # Edit continuum.yaml to point to mongo service
    echo '  mongodb_server: mongodb' >> /etc/continuum/continuum.yaml

ENV CONTINUUM_HOME=/opt/continuum/current

EXPOSE 9090:8080

CMD ["/opt/continuum/current/common/install/init_mongodb.py", "-p", "n813KLVh7sLowt08A66tEQ=="]
