FROM ubuntu:16.04
LABEL maintainer ="a.guillermo.guzman@gmail.com"


RUN apt-get update -y && \
    apt-get upgrade -y && \
    # curl
    apt-get install -y curl && \
    # C
    apt-get install -y build-essential && \
    # These may be unnecessary for the production machine...
    apt-get install -y libkrb5-dev libldap2-dev libsasl2-dev libssl-dev libffi-dev

# Install MongoDB 3.4
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
RUN echo "deb [ arch=amd64 ] http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 multiverse" >> /etc/apt/sources.list.d/mongodb-org-3.4.list
RUN apt-get update && \
    apt-get install -y mongodb-org
RUN mkdir -p /data/db && \
    mkdir -p /var/log/ && \
    touch /var/log/mongod.log

# Download and build latest version of Python
RUN apt-get install -y python python-dev python-pip sudo

WORKDIR /tmp

ARG CONTINUUM_INSTALLER_LINK="https://s3.amazonaws.com/versionone-builds/continuum/installer/continuum-18.0.3.7-S-64886-testing-ssl-with-thirdparty-fix-installer.sh"

RUN set -xe && \
    cd /tmp && \
    curl -o install.sh $CONTINUUM_INSTALLER_LINK && \
    chmod +x install.sh && \
    sed -i 's/source ${WHICHPROFILE}//g' install.sh && \
    ./install.sh -m -p -s

ENV CONTINUUM_HOME=/opt/continuum/current

EXPOSE 9090:8080

CMD mongod
